spring:
  application:
    name: modularMonolith

  datasource:
    url: jdbc:mysql://localhost:3306/springmodulith
    username: root
    password: gevic
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2KB

app:
  security:
    jwt:
      secret: ${JWT_SECRET:votre_cle_par_defaut_pour_le_dev}
      expiration-ms: 86400000

  storage:
    # Le point (.) signifie "la racine du projet en cours"
    upload-dir: ${UPLOAD_DIR:./uploads}